services:
  php:
    container_name: laravel-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment:
      # DB_CONNECTION: sqlite
      # DB_DATABASE: /var/www/storage/database/database.sqlite
      DB_CONNECTION: mysql
      DB_DATABASE: mulsimApp
    command: >
      sh -c "mkdir -p /var/www/storage/database &&
             touch /var/www/storage/database/database.sqlite &&
             chmod -R 777 /var/www/storage &&
             npm install &&
             php-fpm"

  nginx:
    container_name: laravel-nginx
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
